-- Semilla pública. Hechos citados; apertura a juicio ≠ condena.
-- aliases incluye "Loteca" porque así lo busca la gente.

INSERT INTO nodes (id, name, aliases, category, role, period, rnc, summary) VALUES
('p-luis-abinader', 'Luis Rodolfo Abinader Corona', ARRAY['Luis Abinader','Abinader','Luis Abinader Corona','presidente Abinader'], 'persona', 'Presidente de la República', '2020–', NULL,
 'Titular del Poder Ejecutivo. Cargo público oficial; no implica irregularidad.'),
('p-alfredo-pacheco', 'Alfredo Pacheco Osoria', ARRAY['Alfredo Pacheco','Pacheco','presidente Cámara Diputados'], 'persona', 'Presidente de la Cámara de Diputados', '2020–', NULL,
 'Presidente de la Cámara de Diputados. Cargo legislativo oficial; no implica irregularidad.'),
('i-presidencia', 'Presidencia de la República', ARRAY['Presidencia','Palacio Nacional'], 'institucion', NULL, NULL, NULL,
 'Poder Ejecutivo. Nodo ancla para préstamos, nómina y adjudicaciones del Gobierno Central.'),
('i-camara-diputados', 'Cámara de Diputados', ARRAY['Cámara de Diputados','Diputados'], 'institucion', NULL, NULL, NULL,
 'Cámara Baja del Congreso Nacional.'),
('caso-calamar', 'Operación Calamar', ARRAY['Calamar','caso calamar'], 'caso', NULL, '2020–', NULL,
 'Expediente de la Procuraduría por presunta corrupción administrativa (expropiaciones / pagos irregulares). Apertura a juicio de fondo; no es sentencia de culpabilidad.'),
('caso-odebrecht', 'Caso Odebrecht', ARRAY['Odebrecht','Lava Jato RD'], 'caso', NULL, '2016–', NULL,
 'Investigación y procesos penales en RD por sobornos de Odebrecht en obras públicas. Hechos públicos y sentenciados en parte; cada vínculo cita su fuente.'),
('loteka-srl', 'Lotería Electrónica Loteka, S.R.L.', ARRAY['Loteka','Loteca','Sajama'], 'empresa', 'Concesionaria de lotería electrónica', NULL, '1-01-84405-1',
 'Concesionaria autorizada de loterías electrónicas. Antes Sajama, S.A.; el cambio de nombre a Loteka aparece en reportes sobre el Registro Mercantil.'),
('sajama-sa', 'Sajama, S.A.', ARRAY['Sajama'], 'empresa', NULL, '1999–2010', NULL,
 'Razón social previa reportada para la marca Loteka. Socios históricos citados por periodismo de investigación a partir de certificaciones mercantiles.'),
('fixtil-ltd', 'Fixtil Corporation LTD', ARRAY['Fixtil'], 'empresa', 'Sociedad extranjera', NULL, NULL,
 'Reportada en prensa como controlante de Loteka SRL; acciones al portador — el beneficiario final no está claro en fuentes públicas.'),
('p-donald-guerrero', 'Donald Guerrero Ortiz', ARRAY['Donald Guerrero'], 'persona', 'Exministro de Hacienda', '2016–2020', NULL,
 'Enviado a juicio de fondo en Operación Calamar (no condenado por ese auto). Reportes periodísticos lo sitúan como presidente/socio histórico de Sajama/Loteka.'),
('p-angel-lockward', 'Ángel Lockward', ARRAY['Angel Lockward'], 'persona', 'Abogado', NULL, NULL,
 'Enviado a juicio de fondo en Calamar junto a sus empresas, según la Procuraduría y el tribunal de instrucción.'),
('p-piccirillo', 'Luis Miguel Piccirillo McCabe', ARRAY['Piccirillo'], 'persona', 'Exdirector del CEA', NULL, NULL,
 'Enviado a juicio de fondo en Calamar, según cobertura del auto de apertura.'),
('p-claudio-pena', 'Claudio Silver Peña Peña', ARRAY['Claudio Peña'], 'persona', 'Exdirector de Catastro Nacional', NULL, NULL,
 'Enviado a juicio de fondo en Calamar.'),
('p-constanzo', 'Alejandro Antonio Constanzo Sosa', ARRAY['Constanzo'], 'persona', 'Exdirector de Casinos y Juegos de Azar', NULL, NULL,
 'Enviado a juicio de fondo en Calamar.'),
('p-caamano', 'Daniel Omar de Jesús Caamaño Santana', ARRAY['Daniel Caamaño'], 'persona', 'Excontralor General', NULL, NULL,
 'Enviado a juicio de fondo en Calamar.'),
('p-daniel-guerrero', 'Daniel Guerrero Mena', ARRAY['Daniel Guerrero'], 'persona', NULL, NULL, NULL,
 'Citado por el Ministerio Público en la acusación de Calamar en relación con Intercaribe Mercantil.'),
('e-intercaribe', 'Intercaribe Mercantil, S.A.S.', ARRAY['Intercaribe'], 'empresa', NULL, NULL, NULL,
 'Empresa enviada a juicio en Calamar. El MP la vincula a Donald Guerrero y Daniel Guerrero Mena.'),
('e-miqui-trade', 'Miqui Trade, S.R.L.', ARRAY['Miqui Trade'], 'empresa', NULL, NULL, NULL, 'Enviada a juicio de fondo en Calamar.'),
('e-algodonal', 'Sociedad Inmobiliaria El Algodonal, S.R.L.', ARRAY['El Algodonal'], 'empresa', NULL, NULL, NULL, 'Enviada a juicio de fondo en Calamar.'),
('e-britza', 'Britza Inversiones y Construcciones, S.R.L.', ARRAY['Britza'], 'empresa', NULL, NULL, NULL, 'Enviada a juicio de fondo en Calamar.'),
('e-lockward', 'Ángel Lockward & Asociados, S.R.L.', ARRAY['Lockward Asociados'], 'empresa', NULL, NULL, NULL, 'Enviada a juicio de fondo en Calamar.'),
('e-odebrecht', 'Constructora Norberto Odebrecht', ARRAY['Odebrecht','Novonor'], 'empresa', NULL, NULL, NULL,
 'Constructora brasileña. En RD, el caso de sobornos en obras públicas es de dominio público judicial y periodístico.'),
('i-hacienda', 'Ministerio de Hacienda', ARRAY['Hacienda'], 'institucion', NULL, NULL, NULL, NULL),
('i-casinos', 'Dirección de Casinos y Juegos de Azar', ARRAY['Casinos'], 'institucion', NULL, NULL, NULL, NULL),
('i-pgr', 'Procuraduría General de la República', ARRAY['PGR','Ministerio Público'], 'institucion', NULL, NULL, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  aliases = EXCLUDED.aliases,
  summary = EXCLUDED.summary,
  rnc = EXCLUDED.rnc,
  role = EXCLUDED.role;

INSERT INTO edges (source_id, target_id, type, note) VALUES
('p-luis-abinader', 'i-presidencia', 'titular_de', 'Cargo oficial de Presidente de la República.'),
('p-alfredo-pacheco', 'i-camara-diputados', 'preside', 'Presidente de la Cámara de Diputados.'),
('p-donald-guerrero', 'caso-calamar', 'enviado_a_juicio_en', 'Auto de apertura a juicio; no es condena.'),
('p-angel-lockward', 'caso-calamar', 'enviado_a_juicio_en', NULL),
('p-piccirillo', 'caso-calamar', 'enviado_a_juicio_en', NULL),
('p-claudio-pena', 'caso-calamar', 'enviado_a_juicio_en', NULL),
('p-constanzo', 'caso-calamar', 'enviado_a_juicio_en', NULL),
('p-caamano', 'caso-calamar', 'enviado_a_juicio_en', NULL),
('p-daniel-guerrero', 'caso-calamar', 'citado_en_acusacion', 'Según cobertura de la acusación del MP.'),
('e-intercaribe', 'caso-calamar', 'enviada_a_juicio_en', NULL),
('e-miqui-trade', 'caso-calamar', 'enviada_a_juicio_en', NULL),
('e-algodonal', 'caso-calamar', 'enviada_a_juicio_en', NULL),
('e-britza', 'caso-calamar', 'enviada_a_juicio_en', NULL),
('e-lockward', 'caso-calamar', 'enviada_a_juicio_en', NULL),
('p-angel-lockward', 'e-lockward', 'representante_de', NULL),
('p-donald-guerrero', 'e-intercaribe', 'vinculado_por_acusacion_a', 'El MP relaciona la empresa con Guerrero y su hijo.'),
('p-daniel-guerrero', 'e-intercaribe', 'vinculado_por_acusacion_a', NULL),
('p-donald-guerrero', 'i-hacienda', 'dirigio', 'Ministro de Hacienda 2016–2020.'),
('p-constanzo', 'i-casinos', 'dirigio', NULL),
('i-pgr', 'caso-calamar', 'investiga', NULL),
('loteka-srl', 'i-casinos', 'concesionaria_autorizada_por', 'Listado oficial de concesionarios de loterías electrónicas.'),
('sajama-sa', 'loteka-srl', 'antes_llamada', 'Cambio de nombre reportado a partir de asambleas en Registro Mercantil.'),
('p-donald-guerrero', 'sajama-sa', 'reportado_como_presidente_de', 'Periodismo de investigación (certificación mercantil citada). No es ficha oficial actual.'),
('fixtil-ltd', 'loteka-srl', 'reportada_como_controlante_de', 'Prensa: beneficiario final no claro (acciones al portador).'),
('e-odebrecht', 'caso-odebrecht', 'implicada_en', NULL)
ON CONFLICT (source_id, target_id, type) DO NOTHING;

INSERT INTO sources (node_id, kind, label, url, note) VALUES
('p-luis-abinader', 'official', 'Presidencia de la República', 'https://presidencia.gob.do/', NULL),
('p-alfredo-pacheco', 'official', 'Cámara de Diputados', 'https://www.camaradediputados.gob.do/', NULL),
('caso-calamar', 'official', 'Procuraduría — apertura a juicio Calamar', 'https://pgr.gob.do/ministerio-publico-obtiene-apertura-a-juicio-contra-35-de-40-acusados-de-corrupcion-en-expediente-de-la-operacion-calamar/', NULL),
('caso-calamar', 'journalism', 'El Día — empresas enviadas a juicio', 'https://eldia.com.do/fijan-para-el-19-de-agosto-el-juicio-de-fondo-contra-implicados-en-el-caso-calamar/', NULL),
('loteka-srl', 'official', 'Dirección de Casinos — concesionarios', 'https://www.casinos.gob.do/juegos-autorizados/concesionarios-de-loterias-electronicas/', NULL),
('loteka-srl', 'court', 'SCJ — Loteka S.R.L. RNC 1-01-84405-1', 'https://proceso.com.do/wp-content/uploads/2022/07/suprema.pdf', NULL),
('p-donald-guerrero', 'journalism', 'N Digital — Guerrero y Sajama/Loteka', 'https://n.com.do/2022/03/27/loteka-por-anos-pago-impuestos-por-debajo-de-lo-que-establece-ley-donald-guerrero-fue-su-dueno/', 'Basado en certificaciones mercantiles citadas por Nuria.'),
('fixtil-ltd', 'journalism', 'Panorama — Fixtil / Loteka', 'https://panorama.com.do/los-amos-del-azar-el-imperio-silencioso-detras-de-un-negocio-lucrativo/', NULL);
